powerline-daemon -q
POWERLINE_BASH_CONTINUATION=1
POWERLINE_BASH_SELECT=1
. /usr/local/lib/python2.7/site-packages/powerline/bindings/bash/powerline.sh

# bash settings
if [[ -L ~/.bashrc ]];
   then source ~/.bashrc
fi

# core settings
if [[ -L ~/.profile ]];
   then source ~/.profile
fi

echo "Welcome, Alec"
sleep .5
echo "Loading .bashrc"
sleep .5
echo "Loading .profile"
