powerline-daemon -q
POWERLINE_BASH_CONTINUATION=1
POWERLINE_BASH_SELECT=1
. /usr/local/lib/python2.7/site-packages/powerline/bindings/bash/powerline.sh

source ~/Library/init/utils.sh

# bash settings
if [[ -L ~/.bashrc ]];
   then source ~/.bashrc
fi

# core settings
if [[ -L ~/.profile ]];
   then source ~/.profile
fi

GPG_AGENT_INFO=/tmp/gpg-Z74lEJ/S.gpg-agent:25585:1; export GPG_AGENT_INFO;
SSH_AUTH_SOCK=/tmp/gpg-KS5kJr/S.gpg-agent.ssh; export SSH_AUTH_SOCK;
SSH_AGENT_PID=25585; export SSH_AGENT_PID;

e_header "Welcome, Alec"
sleep .5
e_success "Loading .bashrc"
sleep .5
e_success "Loading .profile"

# Setting PATH for Python 3.5
# The original version is saved in .bash_profile.pysave
PATH="/Library/Frameworks/Python.framework/Versions/3.5/bin:${PATH}"
export PATH
